version: "3.9"

services:
  server:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./:/app
    command: bun --hot server/index.ts
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      S3_BUCKET: ${S3_BUCKET}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PORT: ${PORT:-3000}
    ports:
      - "3000:3000"

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "npm ci && npm run dev -- --host"
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
    depends_on:
      - server

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-expenses}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles:
      - db

volumes:
  pgdata:
